
let icons = [
    "https://res.cloudinary.com/dw6ee3vuu/image/upload/v1685450581/carpenterman_lpbudg.png",
    "https://res.cloudinary.com/dw6ee3vuu/image/upload/v1684356392/Mechanic_nxfpf1.png",
    "https://res.cloudinary.com/dw6ee3vuu/image/upload/v1684356392/Electrician_t6jugz.png",
    "https://res.cloudinary.com/dw6ee3vuu/image/upload/v1684356393/Porter_khqttt.png",
    "https://res.cloudinary.com/dw6ee3vuu/image/upload/v1684356393/Painter_bsa5jl.png",
    "https://res.cloudinary.com/dw6ee3vuu/image/upload/v1684356391/Driver_gyyrfq.png",
    "https://res.cloudinary.com/dw6ee3vuu/image/upload/v1684356392/Plumber_wtbe8m.png",
    "https://res.cloudinary.com/dw6ee3vuu/image/upload/v1684356391/Cook_qmhr7k.png",
    "https://res.cloudinary.com/dw6ee3vuu/image/upload/v1684356390/Builder_wf8nlv.png",
    "https://res.cloudinary.com/dw6ee3vuu/image/upload/v1684356392/Landscaper_vyjsz7.png",
    "https://res.cloudinary.com/dw6ee3vuu/image/upload/v1684356393/Security_lo1wqs.png",
    "https://res.cloudinary.com/dw6ee3vuu/image/upload/v1684356391/Construction_qjqach.png",
    "https://res.cloudinary.com/dw6ee3vuu/image/upload/v1684356391/Delivery_epgt7f.png",
    "https://res.cloudinary.com/dw6ee3vuu/image/upload/v1684356391/Dj_wgxdia.png",
    "https://res.cloudinary.com/dw6ee3vuu/image/upload/v1684356392/Maintainance_jmu7gn.png",
    "https://res.cloudinary.com/dw6ee3vuu/image/upload/v1684356391/AppDev_v96n9d.png",
    "https://res.cloudinary.com/dw6ee3vuu/image/upload/v1684356392/Mover_oe4uzt.png",
    "https://res.cloudinary.com/dw6ee3vuu/image/upload/v1684356394/WebDev_ilzfe6.png",
    "https://res.cloudinary.com/dw6ee3vuu/image/upload/v1684356394/Secretary_eh4dnl.png",
    "https://res.cloudinary.com/dw6ee3vuu/image/upload/v1684356393/Plaster_mxtz73.png",
    "https://res.cloudinary.com/dw6ee3vuu/image/upload/v1684356394/Tailor_ncxtfv.png",
    "https://res.cloudinary.com/dw6ee3vuu/image/upload/v1684356393/SandwichMaker_lmcntm.png",
    "https://res.cloudinary.com/dw6ee3vuu/image/upload/v1684356393/Repairer_pv7n5e.png",
    "https://res.cloudinary.com/dw6ee3vuu/image/upload/v1684356394/Server_k1iq5t.png",
    "https://res.cloudinary.com/dw6ee3vuu/image/upload/v1684356394/Solder_q08x0v.png",
    "https://res.cloudinary.com/dw6ee3vuu/image/upload/v1684356390/Cleaner_bnwszw.png",
    "https://res.cloudinary.com/dw6ee3vuu/image/upload/v1685449921/Screenshot_2023-05-30_173136_xf7slg.png",
    "https://res.cloudinary.com/dw6ee3vuu/image/upload/v1684356393/other_jwzeut.png",
]

const cities = [
    // Major Cities
    'Casablanca',
    'Rabat',
    'Fes',
    'Marrakech',
    'Tangier',
    'Agadir',
    'Meknes',
    'Oujda',
    'Kenitra',
    'Tetouan',
    'Temara',
    'Safi',
    'Sale',
    'Mohammedia',
    'Nador',
    'Al Hoceima',
    'Beni Mellal',
    'Taza',
    'Khouribga',
    'El Jadida',

    // Minor Cities
    'Ait Melloul',
    'Ait Ourir',
    'Amizmiz',
    'Aousserd',
    'Asilah',
    'Azemmour',
    'Azrou',
    'Ben Guerir',
    'Beni Ansar',
    'Berkane',
    'Berrechid',
    'Boujdour',
    'Boulemane',
    'Chefchaouen',
    'Dakhla',
    'El Aioun',
    'El Hajeb',
    'El Kelaa des Sraghna',
    'Errachidia',
    'Essaouira',
    'Figuig',
    'Fnideq',
    'Fquih Ben Salah',
    'Guelmim',
    'Guercif',
    'Ifrane',
    'Inezgane',
    'Jerada',
    'Khemisset',
    'Khenifra',
    'Ksar El Kebir',
    'Laayoune',
    'Larache',
    'Martil',
    'Mechra Bel Ksiri',
    'Mediouna',
    'Midelt',
    'Ouarzazate',
    'Oued Zem',
    'Ouezzane',
    'Sefrou',
    'Settat',
    'Sidi Bennour',
    'Sidi Ifni',
    'Sidi Kacem',
    'Sidi Slimane',
    'Skhirat',
    'Smara',
    'Taourirt',
    'Taroudant',
    'Tata',
    'Taza-Al Hoceima-Taounate',
    'Tinghir',
    'Tiznit',
    'Youssoufia',
    'Zagora',
];

export { icons, cities };