
let icons = [
    "https://res.cloudinary.com/dw6ee3vuu/image/upload/v1685545225/carpenter_hanjyl.png",
    "https://res.cloudinary.com/dw6ee3vuu/image/upload/v1685545637/mechanic_krrr1w.png",
    "https://res.cloudinary.com/dw6ee3vuu/image/upload/v1684356392/Electrician_t6jugz.png",
    "https://res.cloudinary.com/dw6ee3vuu/image/upload/v1685545895/porter_nfrfnq.png",
    "https://res.cloudinary.com/dw6ee3vuu/image/upload/v1684356393/Painter_bsa5jl.png",
    "https://res.cloudinary.com/dw6ee3vuu/image/upload/v1684356391/Driver_gyyrfq.png",
    "https://res.cloudinary.com/dw6ee3vuu/image/upload/v1684356392/Plumber_wtbe8m.png",
    "https://res.cloudinary.com/dw6ee3vuu/image/upload/v1685545427/Cook_ulc1oq.png",
    "https://res.cloudinary.com/dw6ee3vuu/image/upload/v1684356390/Builder_wf8nlv.png",
    "https://res.cloudinary.com/dw6ee3vuu/image/upload/v1684356392/Landscaper_vyjsz7.png",
    "https://res.cloudinary.com/dw6ee3vuu/image/upload/v1684356393/Security_lo1wqs.png",
    "https://res.cloudinary.com/dw6ee3vuu/image/upload/v1684356391/Construction_qjqach.png",
    "https://res.cloudinary.com/dw6ee3vuu/image/upload/v1684356391/Delivery_epgt7f.png",
    "https://res.cloudinary.com/dw6ee3vuu/image/upload/v1684356391/Dj_wgxdia.png",
    "https://res.cloudinary.com/dw6ee3vuu/image/upload/v1684356392/Maintainance_jmu7gn.png",
    "https://res.cloudinary.com/dw6ee3vuu/image/upload/v1684356391/AppDev_v96n9d.png",
    "https://res.cloudinary.com/dw6ee3vuu/image/upload/v1684356392/Mover_oe4uzt.png",
    "https://res.cloudinary.com/dw6ee3vuu/image/upload/v1684356394/WebDev_ilzfe6.png",
    "https://res.cloudinary.com/dw6ee3vuu/image/upload/v1684356394/Secretary_eh4dnl.png",
    "https://res.cloudinary.com/dw6ee3vuu/image/upload/v1685545971/plaster_iyqmwr.png",
    "https://res.cloudinary.com/dw6ee3vuu/image/upload/v1685544806/tailorr_psvhpu.png",
    "https://res.cloudinary.com/dw6ee3vuu/image/upload/v1684356393/SandwichMaker_lmcntm.png",
    "https://res.cloudinary.com/dw6ee3vuu/image/upload/v1685545776/repair_vqegoa.png",
    "https://res.cloudinary.com/dw6ee3vuu/image/upload/v1685546053/server_ku7d9h.png",
    "https://res.cloudinary.com/dw6ee3vuu/image/upload/v1684356394/Solder_q08x0v.png",
    "https://res.cloudinary.com/dw6ee3vuu/image/upload/v1684356390/Cleaner_bnwszw.png",
    "https://res.cloudinary.com/dw6ee3vuu/image/upload/v1685449921/Screenshot_2023-05-30_173136_xf7slg.png",
    "https://res.cloudinary.com/dw6ee3vuu/image/upload/v1684356393/other_jwzeut.png",
]

const cities = [
    // Major Cities
    'Casablanca',
    'Rabat',
    'Fes',
    'Marrakech',
    'Tangier',
    'Agadir',
    'Meknes',
    'Oujda',
    'Kenitra',
    'Tetouan',
    'Temara',
    'Safi',
    'Sale',
    'Mohammedia',
    'Nador',
    'Al Hoceima',
    'Beni Mellal',
    'Taza',
    'Khouribga',
    'El Jadida',

    // Minor Cities
    'Ait Melloul',
    'Ait Ourir',
    'Amizmiz',
    'Aousserd',
    'Asilah',
    'Azemmour',
    'Azrou',
    'Ben Guerir',
    'Beni Ansar',
    'Berkane',
    'Berrechid',
    'Boujdour',
    'Boulemane',
    'Chefchaouen',
    'Dakhla',
    'El Aioun',
    'El Hajeb',
    'El Kelaa des Sraghna',
    'Errachidia',
    'Essaouira',
    'Figuig',
    'Fnideq',
    'Fquih Ben Salah',
    'Guelmim',
    'Guercif',
    'Ifrane',
    'Inezgane',
    'Jerada',
    'Khemisset',
    'Khenifra',
    'Ksar El Kebir',
    'Laayoune',
    'Larache',
    'Martil',
    'Mechra Bel Ksiri',
    'Mediouna',
    'Midelt',
    'Ouarzazate',
    'Oued Zem',
    'Ouezzane',
    'Sefrou',
    'Settat',
    'Sidi Bennour',
    'Sidi Ifni',
    'Sidi Kacem',
    'Sidi Slimane',
    'Skhirat',
    'Smara',
    'Taourirt',
    'Taroudant',
    'Tata',
    'Taza-Al Hoceima-Taounate',
    'Tinghir',
    'Tiznit',
    'Youssoufia',
    'Zagora',
];

const country = {
    Morocco: [
        'Casablanca',
        'Rabat',
        'Fes',
        'Marrakech',
        'Tangier',
        'Agadir',
        'Meknes',
        'Oujda',
        'Kenitra',
        'Tetouan',
        'Temara',
        'Safi',
        'Sale',
        'Mohammedia',
        'Nador',
        'Al Hoceima',
        'Beni Mellal',
        'Taza',
        'Khouribga',
        'El Jadida',

        // Minor Cities
        'Ait Melloul',
        'Ait Ourir',
        'Amizmiz',
        'Aousserd',
        'Asilah',
        'Azemmour',
        'Azrou',
        'Ben Guerir',
        'Beni Ansar',
        'Berkane',
        'Berrechid',
        'Boujdour',
        'Boulemane',
        'Chefchaouen',
        'Dakhla',
        'El Aioun',
        'El Hajeb',
        'El Kelaa des Sraghna',
        'Errachidia',
        'Essaouira',
        'Figuig',
        'Fnideq',
        'Fquih Ben Salah',
        'Guelmim',
        'Guercif',
        'Ifrane',
        'Inezgane',
        'Jerada',
        'Khemisset',
        'Khenifra',
        'Ksar El Kebir',
        'Laayoune',
        'Larache',
        'Martil',
        'Mechra Bel Ksiri',
        'Mediouna',
        'Midelt',
        'Ouarzazate',
        'Oued Zem',
        'Ouezzane',
        'Sefrou',
        'Settat',
        'Sidi Bennour',
        'Sidi Ifni',
        'Sidi Kacem',
        'Sidi Slimane',
        'Skhirat',
        'Smara',
        'Taourirt',
        'Taroudant',
        'Tata',
        'Taza-Al Hoceima-Taounate',
        'Tinghir',
        'Tiznit',
        'Youssoufia',
        'Zagora',
    ],
    Algeria: [
        "Algiers",
        "Oran",
        "Constantine",
        "Annaba",
        "Blida",
        "Batna",
        "Djelfa",
        "Sétif",
        "Sidi Bel Abbès",
        "Biskra",
        "Tébessa",
        "El Oued",
        "Skikda",
        "Tiaret",
        "Béjaïa",
        "Tlemcen",
        "Ouargla",
        "Béchar",
        "Mostaganem",
        "Bordj Bou Arréridj",
        "Chlef",
        "Souk Ahras",
        "M'sila",
        "Guelma",
        "Aïn Oussera",
        "Relizane",
        "El Eulma",
        "Laghouat",
        "Oum el Bouaghi",
        "Khenchela",
        "Mascara",
        "Tizi Ouzou",
        "Tamanrasset",
        "Ech Chettia",
        "Ghardaïa",
        "Ksar El Boukhari",
        "Télagh",
        "Hassi Messaoud",
        "Barika",
        "Aïn Beïda",
        "Beni Saf",
        "Aflou",
        "Boumerdès",
        "El Achir",
        "Bougara",
        "Sfizef",
        "Frenda",
        "Chorfa",
        "Berrouaghia",
        "Khemis Miliana",
        "Aïn Sefra",
        "Mila",
        "Djamaa",
        "Meftah",
        "Theniet El Had",
        "Bir el Djir",
        "Chelghoum el Aid",
        "Béni Mered",
        "Rouissat",
        "Aïn Touta",
        "Ténès",
        "El Khroub",
        "Timimoun",
        "Touggourt",
        "Reguiba",
        "Kerkera",
        "Sidi Khaled",
        "Sidi Aïssa",
        "El Attaf",
        "Ben Mehidi",
        "Tebesbest",
        "In Guezzam",
        "El Bayadh",
        "Sougueur",
        "Hennaya",
        "Sig",
        "Boufarik",
        "Cheria",
        "Souma",
        "Dar Chioukh",
        "Bir el Ater",
        "Héliopolis",
        "Tinerkouk",
        "Ouled Djellal",
        "Bordj Zemoura",
        "Boughezoul",
        "Sidi Okba",
        "Boghni",
        "Sidi Moussa",
        "Mazouna",
        "Berrahal",
        "Hammam Bou Hadjar",
        "Bou Tlelis",
        "Fkirina",
        "Tédrara",
        "Mansoura",
        "Zéralda",
        "Béni Amrane",
        "Birine",
        "Ras El Oued",
        "Zemoura",
        "Oued el Abtal",
        "Sidi Ali",
        "Sidi Amrane",
        "Sidi Mérouane",
        "Draa el Mizan",
        "Tala Hamza",
        "Tajananet",
        "Oued Fodda",
        "Taksebt",
        "Médéa",
        "Aïn Bessem",
        "Merouana",
        "Tazmalt",
        "Arhribs",
        "Rouached",
        "Mouzaïa",
        "El Affroun",
        "Barbacha",
        "Tadmaya",
        "Aïn Kercha",
        "Sidi Khaled",
        "Khemis el Khechna",
        "Bougaa",
        "Beni Douala",
        "Tazoult-Lambese",
        "Debila",
        "Tidjelabine",
        "Sidi M'hamed",
        "Beni Zikki",
        "Hennaya",
        "El Malah",
        "Bir el Arch",
        "Amizour",
        "Boudouaou",
        "Dar El Beïda",
        "El Abadia",
        "Zeralda",
        "El Bordj",
        "Khemis el Khechna",
        "Draria",
        "Tadmait",
        "Messaad",
        "Fesdis",
        "Ouled Mimoun",
        "Bouinan",
        "Aïn Arnat",
        "Aïn Benian",
        "Kheneg Mayoum",
        "Chettia",
        "Besbes",
        "Ouargla",
        "Aïn el Melh",
        "Aïn Defla",
        "Beni Haoua",
        "Beni Slimane",
        "El Hadjira",
        "Gharbouz",
        "Ghazaouet",
        "Guelta Zerka",
        "Moudjebara",
        "Tissemsilt",
        "Ouled Addi Guebala",
        "Maghnia",
        "Aïn el Turk",
        "El Hachem",
        "Sougueur",
        "Sidi Naamane",
        "Rouached",
        "Ténès",
        "Draâ Ben Khedda",
        "Sidi Aïch",
        "Zarzara",
        "Hammam Bou Hadjar",
        "Khemis Miliana",
        "Souani",
        "Sig",
        "Aïn Touta",
        "Bordj Zemoura",
        "Bougara",
        "Tazoult",
        "El Aouinet",
        "Tiklat",
        "Béni Saf",
        "Béni Smiel",
        "Guerrouaou",
        "El Haouaita",
        "Tichy",
        "Zighoud Youcef",
        "Thenia",
        "Ben Mehidi",
        "Fkirina",
        "Aïn Fekka",
        "Beni Djellil",
        "Oued El Alleug",
        "El Eulma",
        "Bir el Djir",
        "Tikjda",
        "Timokten",
        "Sidi Abdelli",
        "Chorfa",
        "Boudjima",
        "Azazga",
        "Sedrata",
        "Aïn El Hadjel",
        "Ouled Haddadj",
        "Bir Ghbalou",
        "Ouled Yaïch",
        "Heliopolis",
        "Sidi Ali",
        "El Malah",
        "Sidi Abdallah",
        "El Affroun",
        "Tébessa",
        "Amirouche",
        "Béjaïa",
        "Boghni",
        "Boudjellil",
        "Bouira",
        "Collo",
        "Djamaa",
        "El Kala",
        "El Oued",
        "Ghazaouet",
        "Ghriss",
        "Guelma",
        "Hassi Bahbah",
        "Khenchela",
        "M'sila",
        "Mascara",
        "Medea",
        "Mila",
        "Ouargla",
        "Oum el Bouaghi",
        "Relizane",
        "Saïda",
        "Sétif",
        "Skikda",
        "Souk Ahras",
        "Tamanrasset",
        "Tébessa",
        "Tiaret",
        "Tindouf",
        "Tizi Ouzou",
        "Tlemcen",
    ],
    Egypt: [
        "Cairo",
        "Alexandria",
        "Giza",
        "Shubra el-Khema",
        "Port Said",
        "Suez",
        "El Mahalla el Kubra",
        "El Mansoura",
        "Tanta",
        "Asyut",
        "Fayoum",
        "Zagazig",
        "Ismailia",
        "Khusus",
        "Aswan",
        "Damanhur",
        "El-Minya",
        "Damietta",
        "Luxor",
        "Qena",
        "Beni Suef",
        "Sohag",
        "Shibin el-Kom",
        "Hurghada",
        "Banha",
        "Kafr al-Sheikh",
        "Mallawi",
        "El Arish",
        "Belbeis",
        "10th of Ramadan City",
        "Marsa Matruh",
        "Mit Ghamr",
        "Kafr el-Dawwar",
        "Qalyub",
        "Desouk",
        "Abu Kabir",
        "Girga",
        "Akhmim",
        "El-Matareya",
        "Edko",
        "Bilqas",
        "Zifta",
        "Samalut",
        "Menouf",
        "Senbellawein",
        "Tahta",
        "Bush",
        "Ashmoun",
        "Manfalut",
        "Senuris",
        "Beni Mazar",
        "Faqous",
        "Talkha",
        "Armant",
        "Maghagha",
        "Manzala",
        "Dairut",
        "Kom Ombo",
        "Kafr al-Zayat",
        "Abu Tig",
        "Qis",
        "Edfu",
        "Rosetta",
        "Esna",
        "Dikirnis",
        "Abnub",
        "Tima",
        "Beila",
        "El-Kanater al-Khiria",
        "Al-Fashn",
        "Al-Mansha",
        "Al-Kareen",
        "El-Gamalia",
        "Fuwa",
        "Minya al-Qamh",
        "Kharga",
        "Qus",
        "Khanka",
        "Abu Qirqas",
        "Biba",
        "Samannoud",
        "Minyet al-Nasr",
        "Shibin al-Qanater",
        "Ibshawai",
        "Sherbin",
        "Drib Nigm",
        "Basyoun",
        "Sers el-Lyan",
        "Dishna",
        "Al-Hamool",
        "Farshut",
        "Tala",
        "Ash-Shuhada",
        "Tamiya",
        "Mashtul el-Sook",
        "Sadat City",
        "El-Ghanayem",
        "Itsa",
        "Al-Baliyana",
        "Hosh Issa",
        "Matai",
        "Juhayna",
        "Sidi Salem",
        "Naj Hammadi",
        "Quesna",
        "Hehya",
        "Abul Matamir",
        "El Ubour",
        "El-Badari",
        "Al-Kanayat",
        "At-Tall al-Kabir",
        "El-Delengat",
        "Al-Hammam",
        "Tukh",
        "Bagour",
        "Etay el-Barud",
        "Deir Mawas",
        "Baltim",
        "Abu Hammad",
        "Abu Hummus",
        "Nabaroh",
        "Sharm el-Sheikh",
        "Daraw",
        "Al-Maragha",
        "Sumusta al-Waqf",
        "Al-Wasta",
        "Ihnasiya",
        "Kom Hamadah",
        "Al-Quseir",
        "Qallin",
        "Birkat al-Sab",
        "Safaga",
        "Ezbet el-Borg",
        "Faraskur",
        "Al-Ibrahimiya",
        "El-Santa",
        "Ras Gharib",
        "Sahel Selim",
        "Dar as-Salam",
        "Rafah",
        "Mit Salsil",
        "Al-Husseinieh",
        "Kafr el-Batikh",
        "Kafr Saqr",
        "Qift",
        "Fayed",
        "Saqultah",
        "Wadi al-Natrun",
        "Naqadah",
        "As-Sarw",
        "Awlad Saqr",
        "Sidi Barrani",
        "Al-Basaliyah Bahri",
        "Badr",
        "Sedfa",
        "El-Qantara ash-Sharqiya",
        "Ar-Ruda",
        "Mut",
        "Al-Tur",
        "New Salhia",
        "Ash-Shaykh Zawid",
        "Riyadh",
        "New Beni Suef",
        "Aga",
        "Ad-Dabah",
        "Al-Zarqa",
        "As-Sibaiyah Gharb",
        "Siwa",
        "El-Idwa",
        "Yusuf as-Siddiq",
        "Al-Bayadiyah",
    ],
    UAE: [
        "Abu Dhabi",
        "Dubai",
        "Sharjah",
        "Ajman",
        "Ras Al Khaimah",
        "Fujairah",
        "Umm Al Quwain",
        "Al Ain",
        "Dibba Al-Fujairah",
        "Dibba Al-Hisn",
        "Khor Fakkan",
        "Kalba",
        "Masafi",
        "Madinat Zayed",
        "Liwa Oasis",
        "Al Dhaid",
        "Al Quoz",
        "Jebel Ali",
        "Hatta",
        "Mussafah",
        "Al Hamriyah",
        "Ruwais",
        "Ghayathi",
        "Sila",
        "Das Island",
        "Das Al Khaimah",
        "Dhaid",
        "Al Khaznah",
        "Ar-Rams",
        "Ghalilah",
        "Dibba-Masyaf",
        "Al Wagan",
        "Al Zubara",
        "Diba",
        "Al Heera",
        "Al Rafaah",
        "Al Suwaihan",
        "Hamim",
        "Jabal Dhanna",
        "Liwa",
        "Madinat Khalifa",
        "Madinat Zayed",
        "Mirfa",
        "Mohammed Bin Zayed City",
        "Mughayra",
        "Murbah",
        "Musaffah Industrial Area",
        "Ruwais Industrial Complex",
        "Sweihan",
        "Taweelah",
        "Al Ain Industrial Area",
        "Al Quaa",
        "Al Yahar",
        "Bu Hasa",
        "Ghayl",
        "Ghaylī",
        "Jabal Ali",
        "Ras Al Khor",
        "Wadi Shah",
        "Wadi Sider",
    ],
    Qatar: [
        "Doha",
        "Al Rayyan",
        "Umm Salal",
        "Al Khor",
        "Al Wakrah",
        "Al Khawr",
        "Ash Shamal",
        "Al Daayen",
        "Madinat ash Shamal",
        "Mesaieed",
        "Al Ruwais",
        "Al Ghuwairiyah",
        "Al Jumaliyah",
        "Al Khuwayr",
        "Al Nasraniya",
        "Ar Ru'ays",
        "Dukhan",
        "Fuwayrit",
        "Lusail",
        "Mesaimeer",
        "Simaisma",
        "Al Wakra",
        "Al Wukayr",
        "As Salatah",
        "Muaither",
        "Al Hilal",
        "Al Sadd",
        "Al Muntazah",
        "Old Al Ghanim",
        "New Al Ghanim",
        "Mushayrib",
        "Al Luqta",
        "Abu Samra",
        "Al Karana",
        "Al Utouriya",
        "Leabaib",
        "Al Zubara",
        "Abu Dhalouf",
        "Al Mafjar",
        "Umm Birka",
        "Al Jasrah",
        "Al Sheehaniya",
        "Umm Al Amad",
        "Rawdat Al Hamama",
        "Al Ebb",
        "Al Jeryan",
        "Al Ka`biyah",
        "Al Kharrarah",
        "Al Nasr",
        "Al Rufaa",
        "Al Rayan",
        "Fereej Al Amir",
        "Fereej Al Asiri",
        "Fereej Al Asmakh",
        "Fereej Al Manaseer",
        "Fereej Al Murra",
        "Fereej Al Nasr",
        "Fereej Al Soudan",
        "Fereej Bin Dirham",
        "Fereej Bin Mahmoud",
        "Fereej Bin Omran",
        "Fereej Bin Omran - North",
        "Fereej Bin Omran - South",
        "Fereej Kulaib",
        "Fereej Mohammed Bin Jasim",
        "Fereej Mohammed Bin Jasim",
        "Fereej Mohammed Bin Jasim - East",
        "Fereej Mohammed Bin Jasim - West",
        "Fereej Mohammed Bin Jasim - North",
        "Fereej Mohammed Bin Jasim - South",
        "Fereej Mohammed Bin Jasim - Industrial",
        "Fereej Abdul Aziz",
        "Fereej Al Amir",
        "Fereej Al Asiri",
        "Fereej Al Asmakh",
        "Fereej Al Manaseer",
        "Fereej Al Murra",
        "Fereej Al Nasr",
        "Fereej Al Soudan",
        "Fereej Bin Dirham",
        "Fereej Bin Mahmoud",
        "Fereej Bin Omran",
        "Fereej Bin Omran - North",
        "Fereej Bin Omran - South",
        "Fereej Kulaib",
        "Fereej Mohammed Bin Jasim",
        "Fereej Mohammed Bin Jasim",
        "Fereej Mohammed Bin Jasim - East",
        "Fereej Mohammed Bin Jasim - West",
        "Fereej Mohammed Bin Jasim - North",
        "Fereej Mohammed Bin Jasim - South",
        "Fereej Mohammed Bin Jasim - Industrial",
        "Fereej Abdul Aziz"
    ]
}


export { icons, cities, country };